"""StateLens CLI — Command-line interface.

Provides `statelens init` and `statelens serve` subcommands.
"""

from __future__ import annotations

import argparse
import sqlite3
import sys
from pathlib import Path

STATELENS_DIR = ".statelens"

# Default .env content
DEFAULT_ENV = """\
# StateLens Environment Configuration
# Generated by `statelens init`

# Database path (defaults to .statelens/statelens.db in project root)
STATELENS_DB_PATH=.statelens/statelens.db

# Server settings
STATELENS_HOST=127.0.0.1
STATELENS_PORT=8000

# CORS origins (comma-separated)
STATELENS_CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
"""

# Default config.toml content
DEFAULT_CONFIG = """\
# StateLens Configuration
# Generated by `statelens init`

[server]
host = "127.0.0.1"
port = 8000

[database]
# Path relative to project root
path = ".statelens/statelens.db"

[ui]
# Auto-open browser on `statelens serve`
open_browser = true
"""

# Default features.toml content
DEFAULT_FEATURES = """\
# StateLens Feature Flags
# Generated by `statelens init`
# Enable/disable framework integrations

[frameworks]
langgraph = true
openai_agents = false
mcp = false
crewai = false
mastra = false

[storage]
sqlite = true
"""

# SQL schema for the events table
CREATE_EVENTS_TABLE = """\
CREATE TABLE IF NOT EXISTS events (
    node_id TEXT PRIMARY KEY,
    conversation_id TEXT NOT NULL,
    node_name TEXT NOT NULL,
    node_type TEXT NOT NULL,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    latency_ms REAL NOT NULL,
    status TEXT NOT NULL,
    input TEXT NOT NULL DEFAULT '{}',
    output TEXT NOT NULL DEFAULT '{}',
    state_before TEXT NOT NULL DEFAULT '{}',
    state_after TEXT NOT NULL DEFAULT '{}',
    error TEXT
);

CREATE INDEX IF NOT EXISTS idx_events_conversation_id
ON events (conversation_id);

CREATE INDEX IF NOT EXISTS idx_events_start_time
ON events (start_time);
"""


def init_command(args: argparse.Namespace) -> None:
    """Initialize a .statelens directory in the current project."""
    project_dir = Path.cwd()
    statelens_dir = project_dir / STATELENS_DIR

    if statelens_dir.exists() and not args.force:
        print(f"⚠️  {STATELENS_DIR}/ already exists. Use --force to reinitialize.")
        sys.exit(1)

    print("🔍 StateLens — Initializing project...")
    print()

    # 1. Create .statelens/ directory
    statelens_dir.mkdir(parents=True, exist_ok=True)
    print(f"   ✓ Created {STATELENS_DIR}/")

    # 2. Create .env
    env_file = statelens_dir / ".env"
    env_file.write_text(DEFAULT_ENV)
    print(f"   ✓ Created {STATELENS_DIR}/.env")

    # 3. Create config.toml
    config_file = statelens_dir / "config.toml"
    config_file.write_text(DEFAULT_CONFIG)
    print(f"   ✓ Created {STATELENS_DIR}/config.toml")

    # 4. Create features.toml
    features_file = statelens_dir / "features.toml"
    features_file.write_text(DEFAULT_FEATURES)
    print(f"   ✓ Created {STATELENS_DIR}/features.toml")

    # 5. Create SQLite database with schema
    db_path = statelens_dir / "statelens.db"
    conn = sqlite3.connect(str(db_path))
    conn.execute("PRAGMA journal_mode=WAL")
    conn.executescript(CREATE_EVENTS_TABLE)
    conn.close()
    print(f"   ✓ Created {STATELENS_DIR}/statelens.db")

    # 6. Add .statelens to .gitignore if not already there
    gitignore = project_dir / ".gitignore"
    if gitignore.exists():
        content = gitignore.read_text()
        if ".statelens/" not in content and ".statelens" not in content:
            with gitignore.open("a") as f:
                f.write("\n# StateLens local data\n.statelens/\n")
            print("   ✓ Added .statelens/ to .gitignore")
        else:
            print("   ✓ .gitignore already ignores .statelens/")
    else:
        gitignore.write_text("# StateLens local data\n.statelens/\n")
        print("   ✓ Created .gitignore with .statelens/")

    print()
    print("✅ Done! Next steps:")
    print()
    print("   1. Wrap your graph with observe():")
    print()
    print("      from statelens import observe")
    print("      app = graph.compile()")
    print("      app = observe(app)")
    print()
    print("   2. Run your agent, then view results:")
    print()
    print("      statelens serve")
    print()


def serve_command(args: argparse.Namespace) -> None:
    """Start the StateLens UI server."""
    import webbrowser

    import uvicorn

    # Ensure the app module is importable (validates config)
    import statelens_server.main  # noqa: F401

    host = args.host
    port = args.port

    print("🔍 StateLens — Chrome DevTools for AI Agents")
    print(f"   Server: http://{host}:{port}")
    print(f"   Press Ctrl+C to stop")
    print()

    if not args.no_open:
        webbrowser.open(f"http://{host}:{port}")

    uvicorn.run(
        "statelens_server.main:app",
        host=host,
        port=port,
        reload=False,
    )


def main() -> None:
    """CLI entry point — parses args and dispatches subcommands."""
    parser = argparse.ArgumentParser(
        prog="statelens",
        description="StateLens — Chrome DevTools for AI Agents",
    )
    subparsers = parser.add_subparsers(dest="command")

    # statelens init
    init_parser = subparsers.add_parser("init", help="Initialize .statelens in your project")
    init_parser.add_argument(
        "--force", action="store_true", help="Reinitialize even if .statelens/ exists"
    )

    # statelens serve
    serve_parser = subparsers.add_parser("serve", help="Start the StateLens debug UI")
    serve_parser.add_argument(
        "--port", "-p", type=int, default=8000, help="Port to serve on (default: 8000)"
    )
    serve_parser.add_argument(
        "--host", default="127.0.0.1", help="Host to bind to (default: 127.0.0.1)"
    )
    serve_parser.add_argument(
        "--no-open", action="store_true", help="Don't open browser automatically"
    )

    args = parser.parse_args()

    if args.command == "init":
        init_command(args)
    elif args.command == "serve":
        serve_command(args)
    else:
        parser.print_help()
        sys.exit(1)


if __name__ == "__main__":
    main()
